/**
 * 🎯 共通型定義エクスポート (Common Types Export)
 *
 * 責任:
 * - 共通型定義の統一エクスポート
 * - 型のインポートパス簡素化
 * - 依存関係の明確化
 */

// UI関連の共通型定義
export type {
  TabItem,
  AuthenticatedTabItem,
  AdminMenuItem,
  SettingsMenuItem,
  AdminMenuListProps,
  SupportedLocale,
  ButtonProps,
  MobileHeaderProps,
  SettingGroupProps,
  SettingsCategory,
  SettingsMenuListProps,
  SettingsMenuItemFilter,
  SettingsMenuItemSorter,
  SettingValue,
  AdminMenuItemFilter,
  AdminMenuItemSorter,
  AdminPermissionChecker,
  AvatarGroupProps,
  BadgeVariants,
  ButtonVariants,
  IconButtonProps,
  ButtonGroupProps,
  CardVariant,
  CardSize,
  CardProps,
  CardHeaderProps,
  CardTitleProps,
  CardDescriptionProps,
  CardContentProps,
  CardFooterProps,
  BreadcrumbItem,
  HeaderAction,
  IconInputProps,
  PasswordInputProps,
  SelectOption,
  SelectProps,
  FormFieldProps,
  TimeFormat,
  TimeAlign,
  RelativeTimeProps,
  TimeDisplayProps,
  AbsoluteTimeProps,
  UseTabsOptions,
  UseTabsReturn,
  TabFilterOptions,
  TimelineTabType,
  ProfileTabType,
  WalletTabType,
  EmptyState,
  ListItem,
  HeaderLevel,
  SizeVariant,
  ButtonVariant,
  ButtonSize,
  InputVariant,
  DepositWithdrawTabType,
  BadgeSize,
} from './ui';
